#!/usr/bin/env python
import os
import sys
from os import environ
from os.path import dirname, abspath
from django.core.management import execute_from_command_line
from lisa.server.web import weblisa, googlespeech, manageplugins, interface

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "lisa.server.web.weblisa.settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
